### ISSUE TITLE
dependency-lint error

### ISSUE THREAD

**Issue by js08** [charlierudolph/dependency-lint#13]
Hi,

Hi,

We have tested the dependency-lint package with a sample todo react app. Can you guys tell me why this error is happening.

D:\todomvc>.\node_modules.bin\dependency-lint
D:\todomvc\node_modules\dependency-lint\node_modules\detective\node_modules\acorn\dist\acorn.js:1747
  throw err;
        ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
  at Parser.pp.raise (D:\todomvc\node_modules\dependency-lint\node_modules\detective\node_modules\acorn\dist\acorn.js:1745:13)
  at Parser.pp.parseStatement (D:\todomvc\node_modules\dependency-lint\node_modules\detective\node_modules\acorn\dist\acorn.js:2450:34)
  at Parser.pp.parseTopLevel (D:\todomvc\node_modules\dependency-lint\node_modules\detective\node_modules\acorn\dist\acorn.js:2379:21)
  at Object.parse (D:\todomvc\node_modules\dependency-lint\node_modules\detective\node_modules\acorn\dist\acorn.js:101:12)
  at parse (D:\todomvc\node_modules\dependency-lint\node_modules\detective\index.js:10:18)
  at Function.exports.find (D:\todomvc\node_modules\dependency-lint\node_modules\detective\index.js:45:15)
  at module.exports (D:\todomvc\node_modules\dependency-lint\node_modules\detective\index.js:24:20)
  at RequiredModuleFinder.findInContent (D:\todomvc\node_modules\dependency-lint\src\linter\used_module_finder\required_module_finder.coffee:53:19)
  at D:\todomvc\node_modules\dependency-lint\src\linter\used_module_finder\required_module_finder.coffee:32:21
  at fn (D:\todomvc\node_modules\dependency-lint\node_modules\async\lib\async.js:717:34)
  at D:\todomvc\node_modules\dependency-lint\node_modules\async\lib\async.js:1170:16
  at D:\todomvc\node_modules\dependency-lint\node_modules\async\lib\async.js:172:37
  at D:\todomvc\node_modules\dependency-lint\node_modules\async\lib\async.js:677:43
  at D:\todomvc\node_modules\dependency-lint\node_modules\async\lib\async.js:173:37
  at Immediate._onImmediate (D:\todomvc\node_modules\dependency-lint\node_modules\async\lib\async.js:1163:34)
  at processImmediate [as _immediateCallback](timers.js:367:17)

**Comment by charlierudolph** [comment]
Just released 2.3.0 so the error message should include which file encountered this error. Can you please update and then provide me with more details (such as the file content)? I suspect the file might need to be added to `ignoreFilePatterns` (see the Configuration section of the README) but could be wrong

**Comment by vmc29** [comment]
Hi @charlierudolph 

earlier i got the same error which @js08  mentioned above,

after update to 2.3.0, error changed to 

E:\todomvc>.\node_modules.bin\dependency-lint
Error: UNKNOWN, readlink 'E:\todomvc\node_modules.bin\dependency-lint'

here is the code i used..
https://github.com/rackt/redux/tree/master/examples/todomvc

am i executing it in right way, if not, can you please guide me...

Thanks..

**Comment by charlierudolph** [comment]
@vmc29 had you installed dependency lint locally? The error you are seeing looks like its missing

**Comment by charlierudolph** [comment]
Closing due to lack of response. @vmc29 please reopen if needed
